{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "API Documentation",
        "description": "Express API server with Node.js and MariaDB",
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        }
    },
    "host": "localhost:3000",
    "basePath": "/api",
    "tags": [{
        "name": "Users",
        "description": "API for users in the system"
    }],
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/users": {
            "post": {
                "tags": [
                    "Users"
                ],
                "description": "Create new user in system",
                "parameters": [{
                    "name": "user",
                    "in": "body",
                    "description": "User that we want to create",
                    "schema": {
                        "$ref": "#/definitions/User"
                    }
                }],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "New user is created",
                        "schema": {
                            "$ref": "#/definitions/User Response"
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Get all users in system",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Users List"
                        }
                    }
                }
            },
            "put": {
                "summary": "Update user with given email",
                "tags": [
                    "Users"
                ],
                "parameters": [{
                    "name": "user",
                    "in": "body",
                    "description": "User with new values of properties",
                    "schema": {
                        "$ref": "#/definitions/User"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "User is updated",
                        "schema": {
                            "$ref": "#/definitions/Update User Email"
                        }
                    }
                }
            }
        },
        "/users/{userId}": {
            "parameters": [{
                "name": "userId",
                "in": "path",
                "required": true,
                "description": "ID of user that we want to find",
                "type": "string"
            }],
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Get user with given ID",
                "responses": {
                    "200": {
                        "description": "User is found",
                        "schema": {
                            "$ref": "#/definitions/Get User by ID"
                        }
                    }
                }
            }
        },
        "/users/{userEmail}": {
            "parameters": [{
                "name": "userEmail",
                "in": "path",
                "required": true,
                "description": "Email of the user that we want to delete",
                "type": "string"
            }],
            "delete": {
                "summary": "Delete user with given email address",
                "tags": [
                    "Users"
                ],
                "responses": {
                    "200": {
                        "description": "User is deleted",
                        "schema": {
                            "$ref": "#/definitions/Delete User"
                        }
                    }
                }
            }
        },
        "/statuses": {
            "post": {
                "tags": [
                    "Statuses"
                ],
                "description": "Create new status in system",
                "parameters": [{
                    "name": "status",
                    "in": "body",
                    "description": "Add status for a specific user",
                    "schema": {
                        "$ref": "#/definitions/Status"
                    }
                }],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "New status is created",
                        "schema": {
                            "$ref": "#/definitions/Status Response"
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Statuses"
                ],
                "summary": "Get all statuses in the system",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Statuses List"
                        }
                    }
                }
            },
            "put": {
                "summary": "Update status with given status id",
                "tags": [
                    "Statuses"
                ],
                "parameters": [{
                    "name": "status",
                    "in": "body",
                    "description": "Status with new values of properties",
                    "schema": {
                        "$ref": "#/definitions/Status"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Status is updated",
                        "schema": {
                            "$ref": "#/definitions/Status Id"
                        }
                    }
                }
            }
        },
        "/statuses/{userId}": {
            "parameters": [{
                "name": "userId",
                "in": "path",
                "required": true,
                "description": "ID of the user which status we want to find",
                "type": "string"
            }],
            "get": {
                "tags": [
                    "Statuses"
                ],
                "summary": "Get status with given user ID",
                "responses": {
                    "200": {
                        "description": "Status is found",
                        "schema": {
                            "$ref": "#/definitions/Get Status"
                        }
                    }
                }
            }
        },
        "/statuses/{statusId}": {
            "parameters": [{
                "name": "statusId",
                "in": "path",
                "required": true,
                "description": "ID of the user's status that we want to delete",
                "type": "string"
            }],
            "delete": {
                "summary": "Delete status with given status ID",
                "tags": [
                    "Statuses"
                ],
                "responses": {
                    "200": {
                        "description": "Status is deleted",
                        "schema": {
                            "$ref": "#/definitions/Status Delete"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "User": {
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "uniqueItems": true
                },
                "password": {
                    "type": "string",
                    "uniqueItems": false
                }
            },
            "example": {
                "email": "darth@vader.com",
                "password": "123456"
            }
        },
        "User Response": {
            "properties": {
                "Message": {
                    "type": "string"
                },
                "User": {
                    "type": "string"
                },
                "User_ID": {
                    "type": "integer"
                }
            },
            "example": {
                "Message": "User Added!",
                "User": "darth@vader.com",
                "User_ID": "1"
            }
        },
        "Update User Email": {
            "properties": {
                "Message": {
                    "type": "string"
                }
            },
            "example": {
                "Message": "Updated the password for email darth@vader.com"
            }
        },
        "Delete User": {
            "properties": {
                "Message": {
                    "type": "string"
                }
            },
            "example": {
                "Message": "Deleted the user with email darth@vader.com"
            }
        },
        "Get User by ID": {
            "properties": {
                "Message": {
                    "type": "string"
                },
                "Users": {
                    "type": "array",
                    "$ref": "#/definitions/User Response"
                }
            },
            "example": {
                "Message": "Success",
                "Users": [{
                    "user_id": 1,
                    "user_email": "darth@vader.com",
                    "user_password": "202cb962ac59075b964b07152d234b70",
                    "user_join_date": "2018-03-27T08:38:28.000Z"
                }]
            }
        },
        "Users List": {
            "properties": {
                "Message": {
                    "type": "string"
                },
                "Users": {
                    "type": "array",
                    "$ref": "#/definitions/User Response"
                }
            },
            "example": {
                "Message": "Success",
                "Users": [{
                        "user_id": 1,
                        "user_email": "darth@vader.com",
                        "user_password": "202cb962ac59075b964b07152d234b70",
                        "user_join_date": "2018-03-27T08:38:28.000Z"
                    },
                    {
                        "user_id": 2,
                        "user_email": "obi_wan@theforce.com",
                        "user_password": "e10adc3949ba59abbe56e057f20f883e",
                        "user_join_date": "2018-03-27T08:59:28.000Z"
                    }
                ]
            }
        },
        "Status": {
            "required": [
                "userId",
                "status"
            ],
            "properties": {
                "userId": {
                    "type": "integer",
                    "uniqueItems": true
                },
                "status": {
                    "type": "string",
                    "uniqueItems": false
                }
            },
            "example": {
                "userId": "1",
                "Status": "Currently working for the Galactic Empire"
            }
        },
        "Status Response": {
            "properties": {
                "Message": {
                    "type": "string"
                }
            },
            "example": {
                "Message": "Status Added!"
            }
        },
        "Statuses List": {
            "properties": {
                "Message": {
                    "type": "string"
                },
                "Statuses": {
                    "type": "array",
                    "$ref": "#/definitions/Status Response"
                }
            },
            "example": {
                "Message": "Success",
                "Statuses": [{
                        "user_status_id": 1,
                        "user_id_fk": 1,
                        "status_text": "Currently working for the Galactic Empire",
                        "status_time": "2018-03-28T10:49:45.000Z"
                    },
                    {
                        "user_status_id": 2,
                        "user_id_fk": 2,
                        "status_text": "Currently living in Tatooine",
                        "status_time": "2018-03-28T10:49:45.000Z"
                    }
                ]
            }
        },
        "Status Id": {
            "properties": {
                "Message": {
                    "type": "string"
                }
            },
            "example": {
                "Message": "Status updated"
            }
        },
        "Get Status": {
            "properties": {
                "Message": {
                    "type": "string"
                },
                "Users": {
                    "type": "array",
                    "$ref": "#/definitions/Status Response"
                }
            },
            "example": {
                "Message": "Success",
                "Status": [{
                    "user_status_id": 1,
                    "user_id_fk": 1,
                    "status_text": "Currently working for the Galactic Empire",
                    "status_time": "2018-03-28T10:49:45.000Z"
                }]
            }
        },
        "Status Delete": {
            "properties": {
                "Message": {
                    "type": "string"
                }
            },
            "example": {
                "Message": "Status deleted"
            }
        }
    }
}